server:
  port: 8080
spring:
  application:
      name: EcoNote
  data:
    mongodb:
      uri: mongodb+srv://kiranrajb5882:kiran@cluster0.yl4usri.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: EcoNote
      auto-index-creation: true
